export const sample_med = [
  {
    id: 1,
    name: "Aspirin",
    price: 10.99,
    shops: "Drugs 24",
    dateAdded: new Date("2023-01-15"),
    isFavorite: false,
    imageURL: "img_1.jpg",
  },
  {
    id: 2,
    name: "Paracetamol",
    price: 8.49,
    shops: "Drugs 24",
    dateAdded: new Date("2023-02-03"),
    isFavorite: true,
    imageURL: "img_2.jpg",
  },
  {
    id: 3,
    name: "Ibuprofen",
    price: 15.25,
    shops: "Pharmacy One",
    dateAdded: new Date("2023-02-10"),
    isFavorite: false,
    imageURL: "img_3.jpg",
  },
  {
    id: 4,
    name: "Omeprazole",
    price: 7.99,
    shops: "Pharmacy One",
    dateAdded: new Date("2023-02-18"),
    isFavorite: false,
    imageURL: "img_4.jpg",
  },
  {
    id: 5,
    name: "Lipril",
    price: 12.75,
    shops: "HealthPlus",
    dateAdded: new Date("2023-03-05"),
    isFavorite: true,
    imageURL: "img_5.jpg",
  },
  {
    id: 6,
    name: "Corvalol",
    price: 11.99,
    shops: "HealthPlus",
    dateAdded: new Date("2023-08-05"),
    isFavorite: true,
    imageURL: "img_6.jpg",
  },
];
export const sample_shops = [
  { name: "Drugs 24" },
  { name: "Pharmacy One" },
  { name: "HealthPlus" },
];
